version: "3"
services:
  db: 
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bugtracker
      - MYSQL_USER=mantisbt
      - MYSQL_PASSWORD=mantisbt
    image: 
      mariadb
    ports: 
      - "3306:3306"
    restart:
      always
  mantisbt:
    image: "vimagick/mantisbt:latest"
    links: 
      - db
    ports: 
      - "8989:80"
    restart:
      always
     
  chrome:
    image: selenium/node-chrome:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-default-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-default-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=https://192.168.10.12:4444  
      - SE_NODE_SESSION_TIMEOUT=30
      - SE_SESSION_REQUEST_TIMEOUT=50
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  edge:
    image: selenium/node-edge:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-default-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-default-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=https://localhost:4444
      - SE_NODE_SESSION_TIMEOUT=30 
      - SE_SESSION_REQUEST_TIMEOUT=50
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  firefox:
    image: selenium/node-firefox:4.1.1-20211217
    shm_size: 2gb
    depends_on:
      - selenium-default-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-default-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=https://localhost:4444
      - SE_NODE_SESSION_TIMEOUT=30 
      - SE_SESSION_REQUEST_TIMEOUT=50
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1080

  selenium-default-hub:
    image: selenium/hub:4.1.1-20211217
    container_name: selenium-default-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"